---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-trigger
secrets:
  - name: bitbucketytre-ssh-key
  - name: bitbucket-webhook-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-trigger
roleRef:
  name: tekton-triggers-eventlistener-roles
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: pipeline-trigger
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-trigger
roleRef:
  name: tekton-triggers-eventlistener-clusterroles
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: pipeline-trigger
    kind: ServiceAccount
