apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: maven-pipeline
spec:
  params:
    - name: username
  tasks:
    - name: task-1
      params:
        - name: username
          value: $(params.username)
      taskSpec:
        params:
          - name: username
        steps:
          - image: alpine:3.15
            script: |
              echo "hello $(params.username)"

